 /******************************************************************************
 *
 * Module: PORT
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Ahmed Summra
 ******************************************************************************/
 
#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif
   
/* Pb structure used with Port_Init function 
   
* The Default Pin Configration: 
   *    1.Direction: output 
   *    2.Mode: GPIO (Mode0)
   *   3.Initial value: STD_LOW
   *   4.internal resistor: OFF
   *   5.Pin direction changeable: STD_OFF
   *   6.Pin mode changeable: STD_OFF
*/
    
   const Port_ConfigType Port_Configration = {
     PortConf_PORTA_ID,PortConf_PORTA_PIN0_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTA_ID,PortConf_PORTA_PIN1_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTA_ID,PortConf_PORTA_PIN2_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTA_ID,PortConf_PORTA_PIN3_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTA_ID,PortConf_PORTA_PIN4_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTA_ID,PortConf_PORTA_PIN5_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTA_ID,PortConf_PORTA_PIN6_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTA_ID,PortConf_PORTA_PIN7_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
      
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN0_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN1_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN2_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN3_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN4_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN5_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN6_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTB_ID,PortConf_PORTB_PIN7_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
      
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN0_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN1_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN2_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN3_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN4_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN5_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN6_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTC_ID,PortConf_PORTC_PIN7_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
      
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN0_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN1_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN2_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN3_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN4_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN5_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN6_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTD_ID,PortConf_PORTD_PIN7_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
      
    ,PortConf_PORTE_ID,PortConf_PORTE_PIN0_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTE_ID,PortConf_PORTE_PIN1_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTE_ID,PortConf_PORTE_PIN2_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTE_ID,PortConf_PORTE_PIN3_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTE_ID,PortConf_PORTE_PIN4_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTE_ID,PortConf_PORTE_PIN5_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
      
    ,PortConf_PORTF_ID,PortConf_PORTF_PIN0_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTF_ID,PortConf_PORTF_PIN1_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTF_ID,PortConf_PORTF_PIN2_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTF_ID,PortConf_PORTF_PIN3_ID,PORT_PIN_OUT,PortConf_MODE0_DEG_ID,STD_LOW,OFF,STD_OFF,STD_OFF
    ,PortConf_PORTF_ID,PortConf_PORTF_PIN4_ID,PORT_PIN_IN,PortConf_MODE0_DEG_ID,STD_LOW,PULL_UP,STD_OFF,STD_OFF
      
   };
   
   
   
   
   
   